version: '3'
services:
  node-app:
    restart: on-failure
    image: game-service
    build: 
      context: ./app
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/app
    networks:
      - game_network
    env_file: ./app/.env
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql
    restart: always
    env_file: ./app/.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - "3306:3306"
    networks:
      - game_network
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 8080:80
  #   networks:
  #     - game_network
  #   environment:
  #     PMA_HOST: mysqldb
  #     PMA_USER: root
  #     PMA_PASSWORD: $MYSQL_ROOT_PASSWORD
  #   env_file: ./app/.env
  #   depends_on: 
  #     - mysqldb
networks:
  game_network:
    driver: bridge

volumes: 
  db-config:
  db-data:
